"""empty message

Revision ID: 7eb4f5c06831
Revises: 
Create Date: 2020-02-20 10:22:38.266881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb4f5c06831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('archived_timestamp', sa.DateTime(), nullable=True),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['previous_version_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
