"""empty message

Revision ID: 87e4e9bfccf7
Revises: fa18c75127f3
Create Date: 2020-02-14 21:26:20.025334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4e9bfccf7'
down_revision = 'fa18c75127f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('archived', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('previous_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'item', ['previous_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'previous_version_id')
    op.drop_column('item', 'created')
    op.drop_column('item', 'archived')
    # ### end Alembic commands ###
