"""Added is_archived

Revision ID: b0620bd1bf08
Revises: 7eb4f5c06831
Create Date: 2020-02-20 11:08:17.338066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0620bd1bf08'
down_revision = '7eb4f5c06831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_archived')
    # ### end Alembic commands ###
